# Generated by Django 5.0.6 on 2024-06-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('US-Sport', 'US-Sport'), ('Ballsport', 'Ballsport')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='sport',
            field=models.CharField(choices=[('Golf', 'Golf'), ('Football', 'Fußball'), ('Handball', 'Handball'), ('Basketball', 'Basketball')], default='', max_length=20),
        ),
    ]
