# Generated by Django 5.0.6 on 2024-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmflix', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('US-Sport', 'US-Sport'), ('Ballsport', 'Ballsport')], max_length=20, null=True),
        ),
    ]
