# Generated by Django 5.0.6 on 2024-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmflix', '0004_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('ussport', 'US-Sport'), ('ballsport', 'Ballsport')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='sport',
            field=models.CharField(choices=[('golf', 'Golf'), ('football', 'Fußball'), ('handball', 'Handball'), ('basketball', 'Basketball')], default='', max_length=20),
        ),
    ]
