# Generated by Django 5.0.6 on 2024-09-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmflix', '0006_icon_alter_video_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.FileField(upload_to='icons/'),
        ),
    ]
